on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Julian/setup-lean@v1
    - run: lake build

# steps:
# - name:
#   run: |
#     lean .\Mathematics.lean
#     # lean .\Mathematics\**\*.lean
